var index = argument0; ///@param index
var returnType = argument1; ///@param returnType
if(index>=0 and index<length){
	
	if(map_data(global.itemData,itemDataClass,componentMap[refMap[index]])="attachment"){
		if(returnType = "x"){
			return spaceshipSpriteOffset+x-sprite_xoffset+rotate_around_point(boolean_return(rotationMap[refMap[index]] = 180,gridSize*(1-map_data(global.itemData,itemDataWidth,componentMap[refMap[index]])),0)+boolean_return(rotationMap[refMap[index]]=270,gridSize*(1-map_data(global.itemData,itemDataHeight,componentMap[refMap[index]])),0)+((gridSize/2)*map_data(global.itemData,itemDataWidth,componentMap[refMap[index]])*(1-((rotationMap[refMap[index]] mod 180)/90)))+((gridSize/2)*map_data(global.itemData,itemDataHeight,componentMap[refMap[index]])*(((rotationMap[refMap[index]] mod 180)/90)))+(gridX[refMap[index]]*gridSize)+(rotate_around_point(map_data(global.itemData,itemDataCogX,componentMap[refMap[index]]),map_data(global.itemData,itemDataCogY,componentMap[refMap[index]]),0,0,rotationMap[refMap[index]]+90,"x")*flipMap[refMap[index]]),boolean_return(rotationMap[refMap[index]]=90,gridSize*(1-map_data(global.itemData,itemDataWidth,componentMap[refMap[index]])),0)+boolean_return(rotationMap[refMap[index]]=180,gridSize*(1-map_data(global.itemData,itemDataHeight,componentMap[refMap[index]])),0)+((gridSize/2)*map_data(global.itemData,itemDataHeight,componentMap[refMap[index]])*(1-((rotationMap[refMap[index]] mod 180)/90)))+((gridSize/2)*map_data(global.itemData,itemDataWidth,componentMap[refMap[index]])*(((rotationMap[refMap[index]] mod 180)/90)))+(gridY[refMap[index]]*gridSize)+(rotate_around_point(map_data(global.itemData,itemDataCogX,componentMap[refMap[index]]),map_data(global.itemData,itemDataCogY,componentMap[refMap[index]]),0,0,rotationMap[refMap[index]]+90,"y")*flipMap[refMap[index]]),sprite_xoffset-spaceshipSpriteOffset,sprite_yoffset-spaceshipSpriteOffset,dir,"x");
		}
		return spaceshipSpriteOffset+y-sprite_yoffset+rotate_around_point(boolean_return(rotationMap[refMap[index]] = 180,gridSize*(1-map_data(global.itemData,itemDataWidth,componentMap[refMap[index]])),0)+boolean_return(rotationMap[refMap[index]]=270,gridSize*(1-map_data(global.itemData,itemDataHeight,componentMap[refMap[index]])),0)+((gridSize/2)*map_data(global.itemData,itemDataWidth,componentMap[refMap[index]])*(1-((rotationMap[refMap[index]] mod 180)/90)))+((gridSize/2)*map_data(global.itemData,itemDataHeight,componentMap[refMap[index]])*(((rotationMap[refMap[index]] mod 180)/90)))+(gridX[refMap[index]]*gridSize)+(rotate_around_point(map_data(global.itemData,itemDataCogX,componentMap[refMap[index]]),map_data(global.itemData,itemDataCogY,componentMap[refMap[index]]),0,0,rotationMap[refMap[index]]+90,"x")*flipMap[refMap[index]]),boolean_return(rotationMap[refMap[index]]=90,gridSize*(1-map_data(global.itemData,itemDataWidth,componentMap[refMap[index]])),0)+boolean_return(rotationMap[refMap[index]]=180,gridSize*(1-map_data(global.itemData,itemDataHeight,componentMap[refMap[index]])),0)+((gridSize/2)*map_data(global.itemData,itemDataHeight,componentMap[refMap[index]])*(1-((rotationMap[refMap[index]] mod 180)/90)))+((gridSize/2)*map_data(global.itemData,itemDataWidth,componentMap[refMap[index]])*(((rotationMap[refMap[index]] mod 180)/90)))+(gridY[refMap[index]]*gridSize)+(rotate_around_point(map_data(global.itemData,itemDataCogX,componentMap[refMap[index]]),map_data(global.itemData,itemDataCogY,componentMap[refMap[index]]),0,0,rotationMap[refMap[index]]+90,"y")*flipMap[refMap[index]]),sprite_xoffset-spaceshipSpriteOffset,sprite_yoffset-spaceshipSpriteOffset,dir,"y");
	}
	else{
		if(returnType = "x"){
			return spaceshipSpriteOffset+x-sprite_xoffset+rotate_around_point(((gridSize/2)*1*(1-((rotationMap[refMap[index]] mod 180)/90)))+((gridSize/2)*(((rotationMap[refMap[index]] mod 180)/90)))+(gridX[refMap[index]]*gridSize),((gridSize/2)*1*(1-((rotationMap[refMap[index]] mod 180)/90)))+((gridSize/2)*(((rotationMap[refMap[index]] mod 180)/90)))+(gridY[refMap[index]]*gridSize),sprite_xoffset-spaceshipSpriteOffset,sprite_yoffset-spaceshipSpriteOffset,dir,"x");
		}
		return spaceshipSpriteOffset+y-sprite_yoffset+rotate_around_point(((gridSize/2)*1*(1-((rotationMap[refMap[index]] mod 180)/90)))+((gridSize/2)*(((rotationMap[refMap[index]] mod 180)/90)))+(gridX[refMap[index]]*gridSize),((gridSize/2)*1*(1-((rotationMap[refMap[index]] mod 180)/90)))+((gridSize/2)*(((rotationMap[refMap[index]] mod 180)/90)))+(gridY[refMap[index]]*gridSize),sprite_xoffset-spaceshipSpriteOffset,sprite_yoffset-spaceshipSpriteOffset,dir,"y");
	}

}


return -1;
